### ISSUE TITLE
Where's the run_trained_finetuned_model.sh?

### ISSUE THREAD

**Issue by jsrdcht** [roym899/abandoned_bag_detection#1]
Hello,i found the **trained model** in **run_trained_finetuned_model.sh**  missed when I tried to use the project,could you please fix it?

**Comment by roym899** [comment]
I've updated the link. It should download a finetuned model now.

**Comment by gurushreyaas2003** [comment]
Hello, I also found problem in running the **run_trained_finetuned_model.sh** , it says the shared file or folder link is removed.

**Comment by roym899** [comment]
Updated the link.
